### LIBRERIE

In [1]:
import pandas as pd
import numpy as np

### CARICO IL DATASET IN MEMORIA

In [2]:
df = pd.read_csv('C:\\Users\\cuomo\\Desktop\\tesina sistemi intelligenti per internet\\datasets\\ratings.csv')
df_film = pd.read_csv('C:\\Users\\cuomo\\Desktop\\tesina sistemi intelligenti per internet\\datasets\\movies.csv')
user=1

In [3]:
df.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
df.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [5]:
df.shape

(100836, 4)

## SPLIT DATI TRAIN E TEST

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(df, test_size = 0.2, random_state = 42)

## CREAZIONE RATING MATRIX

In [7]:
user_data = X_train.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

In [8]:
user_data.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  191005  193565  193571  193573  193579  193581  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193583  193585  193587  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 8983 columns]

In [9]:
user_data.tail()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
606         2.5     0.0     0.0     0.0     0.0     0.0     2.5     0.0   
607         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
608         2.5     2.0     2.0     0.0     0.0     0.0     0.0     0.0   
609         3.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
610         5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  191005  193565  193571  193573  193579  193581  \
userId                   ...                                                   
606         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
607         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
608         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
609         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
610         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193583  193585  193587  193609  
userId                                   
606         0.0     0.0     0.0     0.0  
607         0.0     0.0     0.0     0.0  
608         0.0     0.0     0.0     0.0  
609         0.0     0.0     0.0     0.0  
610         0.0     0.0     0.0     0.0  

[5 rows x 8983 columns]

## COPIA TRAIN E TEST

In [10]:
dummy_train = X_train.copy()
dummy_test = X_test.copy()

## FILM NON REATED DALL'UTENTE SONO TAGGATI CON 0 SUL DUMMY_TRAIN, CON 1 SUL DUMMY_TEST

In [11]:
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x > 0 else 1)

In [12]:
dummy_train = dummy_train.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(1)

dummy_test = dummy_test.pivot(index ='userId', columns = 'movieId', values = 'rating').fillna(0)

## COSENO SIMILARITA'

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(user_data)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)
print(user_similarity.shape)

[[1.         0.01631391 0.04902077 ... 0.23281083 0.11217366 0.14390178]
 [0.01631391 1.         0.         ... 0.05561043 0.0324038  0.0758095 ]
 [0.04902077 0.         1.         ... 0.00943339 0.         0.03130872]
 ...
 [0.23281083 0.05561043 0.00943339 ... 1.         0.11037068 0.26088589]
 [0.11217366 0.0324038  0.         ... 0.11037068 1.         0.05797092]
 [0.14390178 0.0758095  0.03130872 ... 0.26088589 0.05797092 1.        ]]
(610, 610)


In [14]:
user_predicted_ratings = np.dot(user_similarity, user_data)
user_predicted_ratings

array([[1.02577252e+02, 4.78380457e+01, 2.36818977e+01, ...,
        2.40398835e-02, 2.40398835e-02, 2.42017132e-01],
       [3.21333213e+01, 1.41809490e+01, 3.44725299e+00, ...,
        2.43584645e-01, 2.43584645e-01, 4.72714637e-01],
       [6.01836395e+00, 2.74279977e+00, 1.50865958e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.23967503e+02, 6.54655744e+01, 2.62278039e+01, ...,
        4.49926506e-02, 4.49926506e-02, 7.48581243e-01],
       [8.62259885e+01, 4.26235337e+01, 1.47195042e+01, ...,
        0.00000000e+00, 0.00000000e+00, 5.93470422e-02],
       [1.00615941e+02, 4.83638588e+01, 1.43500347e+01, ...,
        3.66837078e-01, 3.66837078e-01, 9.59369989e-01]])

## SONO STATI PREDETTI TUTTI I FILM, ANCHE QUELLI CHE L'UTENTE HA GIA VISIONATO

In [15]:
user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)
user_final_ratings.head()

movieId     1          2          3         4          5          6       \
userId                                                                     
1         0.000000  47.838046   0.000000  1.677755  12.377902   0.000000   
2        32.133321  14.180949   3.447253  0.173732   3.057459  13.183156   
3         6.018364   2.742800   1.508660  0.075733   0.493866   4.558324   
4        64.814213  29.751614  12.363810  0.961803   7.976059  32.364338   
5        75.894188  44.351569  15.285370  3.251044  15.507294  39.318814   

movieId     7         8         9          10      ...    191005    193565  \
userId                                             ...                       
1        17.349972  2.974873  4.280981  58.319855  ...  0.030908  0.024040   
2         2.652851  0.631876  0.570213  13.399607  ...  0.313180  0.243585   
3         0.830950  0.165717  0.197867   3.763907  ...  0.000000  0.000000   
4        13.216842  1.790811  2.401999  34.534155  ...  0.053430  0.041557   
5        19.789428  3.276160  2.535738  58.817361  ...  0.000000  0.000000   

movieId    193571    193573    193579    193581    193583    193585    193587  \
userId                                                                          
1        0.027474  0.027474  0.024040  0.027474  0.024040  0.024040  0.024040   
2        0.278382  0.278382  0.243585  0.278382  0.243585  0.243585  0.243585   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.047493  0.047493  0.041557  0.047493  0.041557  0.041557  0.041557   
5        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

movieId    193609  
userId             
1        0.242017  
2        0.472715  
3        0.000000  
4        0.186424  
5        0.167847  

[5 rows x 8983 columns]

## SI PREDICONO I PRIMI 30 FILM CHE POTREBBERO PIACERE ALL'UTENTE 1

In [16]:
ls = user_final_ratings.iloc[user-1].sort_values(ascending = False)[0:100]
_ls=[]

for item in ls.iteritems():
    _ls.append(item)

print(_ls[0])

(318, 152.41875870294163)


In [17]:
ll = []
for item in _ls:
    title=df_film.loc[df_film['movieId'] == item[0]].iloc[0]['title']
    score = item[1]
    ll.append([title, score])
    
suggestions = pd.DataFrame(ll, columns = ['Movie', 'Score'])


print("****TOP 30 SUGGESTIONS FOR YOU:****\n")
suggestions.head(30)

****TOP 30 SUGGESTIONS FOR YOU:****



Movie       Score
0                    Shawshank Redemption, The (1994)  152.418759
1                   Terminator 2: Judgment Day (1991)  116.586712
2   Raiders of the Lost Ark (Indiana Jones and the...  112.929267
3                               Godfather, The (1972)  101.944324
4   Lord of the Rings: The Fellowship of the Ring,...   90.680206
5                             Sixth Sense, The (1999)   89.410122
6                                    Apollo 13 (1995)   86.797747
7           Twelve Monkeys (a.k.a. 12 Monkeys) (1995)   84.788341
8                                      Aladdin (1992)   84.256649
9                               Lion King, The (1994)   83.500668
10                                   True Lies (1994)   82.603201
11                   Men in Black (a.k.a. MIB) (1997)   80.949915
12                                   Gladiator (2000)   80.203100
13  Lord of the Rings: The Return of the King, The...   79.365801
14                                       Alien (1979)   78.807628
15                                       Shrek (2001)   77.986828
16                                    Die Hard (1988)   76.837594
17                                     Memento (2000)   75.188851
18                     Godfather: Part II, The (1974)   74.658039
19                                       Speed (1994)   73.183618
20      Lord of the Rings: The Two Towers, The (2002)   71.673348
21                           Good Will Hunting (1997)   69.968295
22                                      Aliens (1986)   68.682569
23  Pirates of the Caribbean: The Curse of the Bla...   67.285314
24             One Flew Over the Cuckoo's Nest (1975)   66.900821
25                                Blade Runner (1982)   66.423679
26                        Beauty and the Beast (1991)   65.819939
27                          American History X (1998)   65.284891
28  Léon: The Professional (a.k.a. The Professiona...   65.044452
29                          Fifth Element, The (1997)   64.863830